# ref: <https://wiki.metacubex.one/config/>

allow-lan: true
bind-address: "*"
lan-allowed-ips:
  - 100.64.0.0/10 # tailscale
  - 127.0.0.0/8 # loopback
  - 172.16.0.0/12 # docker
  - ::1/128 # loopback
skip-auth-prefixes:
  - 127.0.0.0/8 # loopback
  - ::1/128 # loopback
log-level: warning
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile:
  store-selected: true
  store-fake-ip: true
unified-delay: true
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 24 # hours
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb

# ref: <https://dns.icoa.cn/>
dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver:
    - 101.6.6.6 # TUNA DNS666
    - system
    - 119.29.29.29 # DNSPod Public DNS
    - 223.5.5.5 # é˜¿é‡Œäº‘å…¬å…± DNS
  proxy-server-nameserver:
    - https://101.6.6.6/dns-query
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - system
  direct-nameserver:
    - https://101.6.6.6/dns-query
    - system
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  direct-nameserver-follow-policy: false
  nameserver:
    - https://101.6.6.6/dns-query
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: cn
    geosite:
      - geolocation-!cn
      - gfw

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

mixed-port: 7892

rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT # block QUIC

  - DOMAIN-SUFFIX,shenmi.link,CitrusLab Emby

  # domain
  - RULE-SET,domain-direct,DIRECT
  - RULE-SET,domain-domestic,DIRECT
  - RULE-SET,domain-local,DIRECT
  - RULE-SET,domain-ai,AI
  - RULE-SET,domain-download,Download
  - RULE-SET,domain-stream,Stream
  - RULE-SET,domain-telegram,PROXY
  - RULE-SET,domain-global,PROXY

  # ipcidr
  - RULE-SET,ipcidr-domestic,DIRECT
  - RULE-SET,ipcidr-local,DIRECT
  - RULE-SET,ipcidr-stream,Stream
  - RULE-SET,ipcidr-telegram,PROXY
  - RULE-SET,ipcidr-global,PROXY

  - MATCH,PROXY

__rule-providers-anchors:
  classical: &classical
    type: http
    behavior: classical
    format: text
    interval: 86400
  domain: &domain
    type: http
    behavior: domain
    format: mrs
    interval: 86400
  ipcidr: &ipcidr
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400

rule-providers:
  # ðŸ¤– AI
  domain-ai:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/ai.domain.mrs
    path: ./rules/ai.domain.mrs

  # ðŸŽ¯ Direct
  domain-direct:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/direct.domain.mrs
    path: ./rules/direct.domain.mrs

  # ðŸ“ Domestic
  domain-domestic:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/domestic.domain.mrs
    path: ./rules/domestic.domain.mrs
  ipcidr-domestic:
    <<: *ipcidr
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/domestic.ipcidr.mrs
    path: ./rules/domestic.ipcidr.mrs

  # ðŸ“¥ Download
  domain-download:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/download.domain.mrs
    path: ./rules/download.domain.mrs

  # ðŸŒ Global
  domain-global:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/global.domain.mrs
    path: ./rules/global.domain.mrs
  ipcidr-global:
    <<: *ipcidr
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/global.ipcidr.mrs
    path: ./rules/global.ipcidr.mrs

  # â™¾ï¸ Local
  domain-local:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/local.domain.mrs
    path: ./rules/local.domain.mrs
  ipcidr-local:
    <<: *ipcidr
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/local.ipcidr.mrs
    path: ./rules/local.ipcidr.mrs

  # ðŸ“º Stream
  domain-stream:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/stream.domain.mrs
    path: ./rules/stream.domain.mrs
  ipcidr-stream:
    <<: *ipcidr
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/stream.ipcidr.mrs
    path: ./rules/stream.ipcidr.mrs

  # âœˆï¸ Telegram
  domain-telegram:
    <<: *domain
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/telegram.domain.mrs
    path: ./rules/telegram.domain.mrs
  ipcidr-telegram:
    <<: *ipcidr
    url: https://testingcf.jsdelivr.net/gh/liblaf/route-rules@mihomo/mihomo/telegram.ipcidr.mrs
    path: ./rules/telegram.ipcidr.mrs
